---

- hosts: all
  become: true
  tasks:
  
  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]  

  - name: Install apache2 package
    apt:
      name: apache2
      state: latest  
    when: ansible_distribution == "Ubnuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest      
    when: ansible_distribution == "Ubnuntu"     
  
  - name: Update repository index
    yum:
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: Install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

