- name: Add ssh key for simone
  authorized_key:
    user: simone
    key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIErfOOULnQ1sAcoBpcFxS7L9EXV4gR2rRsqaL/Dt7ExN “users_ansible”'

- name: generate sshd_config file from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}" 
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd  



